SET VERIFY OFF
conn /as sysdba
set echo on
spool /opt/oracle/crdb/CreateDBFiles.log append
CREATE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/cdbdev/users01.dbf' SIZE 10M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE 32G  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
spool off
